### PR TITLE
Make analytic  (uniform, Gaussian, and Airy)  beams work

### PR DESCRIPTION
**Pull request by lwhitler**
Quick fixes to the Gaussian and Airy analytic beam models to make their signatures into what the Fourier mode calculation expects, and adding a uniform beam model

### CODE REVIEW

**Comment by steven-murray** [comment]
It looks like it's failing on a newer version of `numba`. You might have to restrict `numba<0.49.0` until we get it working with later versions.

**Review by steven-murray — APPROVED** [review]
This all looks good to me. We'll have to wait for tests to pass though.

**Comment by steven-murray** [comment]
It's now complaining that `tests/travis_install.sh` doesn't exist... but you didn't delete it so....

**Comment by lwhitler** [comment]
I think that was me being stupid with quotation marks, I just pushed an attempt at a fix

**Review by plaplant — APPROVED** [review]
Thanks @lwhitler! These changes look good to me. I'm happy to merge anytime.

**Pull request merged**
